[sources.vector_metrics]
type = "internal_metrics"
scrape_interval_secs = 15

[transforms.filter_unwanted_vector_metrics]
type = "filter"
inputs = ["vector_metrics"]
  [transforms.filter_unwanted_vector_metrics.condition]
  type = "vrl"
  source = '''
    includes(
      [
        "events_discarded_total",
      ],
      .name,
    )
  '''

[transforms.add_vector_metrics_prefix]
type = "remap"
inputs = ["filter_unwanted_vector_metrics"]
source = """
  .name = "vector_" + string!(.name)
"""
