apiVersion: 1

datasources:
-  access: proxy
   jsonData:
     defaultBucket: metrics
     organization: observability
     tlsSkipVerify: true
     version: Flux
   name: Metrics
   secureJsonData:
     token: $INFLUX_API_TOKEN
   type: influxdb
   url: http://influx-db
