[sources.node_metrics]
type = "prometheus_scrape"
endpoints = ["https://kubernetes.default/api/v1/nodes/${VECTOR_SELF_NODE_NAME}/proxy/metrics/cadvisor"]
scrape_interval_secs = 15
  [sources.node_metrics.auth]
  strategy = "bearer"
  token = "${KUBERNETES_API_TOKEN}"
  [sources.node_metrics.tls]
  enabled = true
  ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

[transforms.node_metrics_routing]
type = "route"
inputs = ["node_metrics"]
  [transforms.node_metrics_routing.route]
  cpu = 'contains(.name, "cpu")'
  memory = 'contains(.name, "memory")'
  network = 'contains(.name, "network")'
