[transforms.filter_unwanted_memory_node_metrics]
type = "filter"
inputs = ["node_metrics_routing.memory"]
  [transforms.filter_unwanted_memory_node_metrics.condition]
  type = "vrl"
  source = 'includes(["container_memory_usage_bytes", "machine_memory_bytes"], .name)'
