[transforms.filter_unwanted_network_node_metrics]
type = "filter"
inputs = ["node_metrics_routing.network"]
  [transforms.filter_unwanted_network_node_metrics.condition]
  condition = """
    includes(["container_network_receive_bytes_total", "container_network_transmit_bytes_total"], .name) &&
    !is_empty(.tags.pod)
  """

[transforms.remove_network_node_metrics_fields]
type = "remap"
inputs = ["filter_unwanted_network_node_metrics"]
source = """
  del(.tags.id)
  del(.tags.image)
  del(.tags.name)
"""
