[transforms.filter_unwanted_network_node_metrics]
type = "filter"
inputs = ["node_metrics_routing.network"]
  [transforms.filter_unwanted_network_node_metrics.condition]
  type = "vrl"
  source = 'includes(["container_network_receive_bytes_total", "container_network_transmit_bytes_total"], .name)'
