{
 "title": "Host Metrics",
 "tags": [ "linux" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node:",
    "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"host.cpu_seconds_total\")\n  |> keep(columns: [\"node\"])\n  |> distinct(column: \"node\")\n  |> group()\n"
   },
   { "name": "interval", "label": "Interval:", "query": "1m,5m,15m,30m,1h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Node Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Average CPU usage of the recent 2min ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "cpu_usage_percent = from(bucket: \"metrics\")\n  |> range(start: -2m)\n  |> filter(fn: (r) => r._measurement == \"host.cpu_seconds_total\")\n  |> drop(columns: [\"collector\", \"cpu\", \"host\", \"metric_type\"])\n  |> mean()\n  |> pivot(rowKey: [\"node\"], columnKey: [\"mode\"], valueColumn: \"_value\")\n  |> reduce(\n       fn: (r, accumulator) => ({_value: (r.nice + r.system + r.user) / (r.idle + r.nice + r.system + r.user)}),\n       identity: { _value: 0.0 }\n     )\n\nif \"${node}\" == \"all\"\nthen cpu_usage_percent\n  |> group()\n  |> mean()\n  |> yield(name: \"cpu_usage_percent\")\nelse cpu_usage_percent\n  |> filter(fn: (r) => r.node == \"${node}\")\n  |> yield(name: \"cpu_usage_percent\")"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Average memory usage of the recent 2min",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "memory_usage_percent = from(bucket: \"metrics\")\n  |> range(start: -2m)\n  |> filter(fn: (r) => r._measurement == \"host.memory_total_bytes\" or r._measurement == \"host.memory_used_bytes\")\n  |> drop(columns: [\"collector\", \"host\", \"metric_type\"])\n  |> mean()\n  |> pivot(rowKey: [\"node\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n  |> reduce(\n       fn: (r, accumulator) => ({_value: r[\"host.memory_used_bytes\"] / r[\"host.memory_total_bytes\"]}),\n       identity: { _value: 0.0 }\n     )\n\nif \"${node}\" == \"all\"\nthen memory_usage_percent\n  |> group()\n  |> mean()\n  |> yield(name: \"memory_usage_percent\")\nelse memory_usage_percent\n  |> filter(fn: (r) => r.node == \"${node}\")\n  |> yield(name: \"memory_usage_percent\")"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "filesystem_usage_percent = from(bucket: \"metrics\")\n  |> range(start: -2m)\n  |> filter(fn: (r) => r.mountpoint == \"/\" and (r._measurement == \"host.filesystem_total_bytes\" or r._measurement == \"host.filesystem_used_bytes\"))\n  |> last()\n  |> drop(columns: [\"collector\", \"device\", \"filesystem\", \"host\", \"metric_type\", \"mountpoint\"])\n  |> pivot(rowKey: [\"node\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n  |> reduce(\n       fn: (r, accumulator) => ({_value: r[\"host.filesystem_used_bytes\"] / r[\"host.filesystem_total_bytes\"]}),\n       identity: { _value: 0.0 }\n     )\n\nif \"${node}\" == \"all\"\nthen filesystem_usage_percent\n  |> group()\n  |> mean()\n  |> yield(name: \"filesystem_usage\")\nelse filesystem_usage_percent\n  |> filter(fn: (r) => r.node == \"${node}\")\n  |> yield(name: \"filesystem_usage\")"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "uptime = from(bucket: \"metrics\")\n  |> range(start: -2m)\n  |> filter(fn: (r) => r._measurement == \"host.uptime\")\n  |> last()\n  |> keep(columns: [\"_value\", \"node\"])\n\nif \"${node}\" == \"all\"\n  then uptime\n    |> group()\n    |> max()\n    |> yield(name: \"uptime\")\n  else uptime\n    |> filter(fn: (r) => r.node == \"${node}\")\n    |> yield(name: \"uptime\")"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "cpu_cores_total = from(bucket: \"metrics\")\n  |> range(start: -2m)\n  |> filter(fn: (r) => r._measurement == \"host.cpu_seconds_total\")\n  |> last()\n  |> keep(columns: [\"cpu\", \"node\"])\n  |> group(columns: [\"node\"])\n  |> rename(columns: {\"cpu\": \"_value\"},)\n  |> toInt()\n  |> max()\n  |> map(fn: (r) => ({ r with _value: r._value + 1 }))\n  |> rename(columns: {\"_value\": \"cpu_cores_total\"})\n\ncpu_usage_percent = from(bucket: \"metrics\")\n  |> range(start: -2m)\n  |> filter(fn: (r) => r._measurement == \"host.cpu_seconds_total\")\n  |> keep(columns: [\"_value\", \"node\", \"mode\"])\n  |> mean()\n  |> pivot(rowKey: [\"node\"], columnKey: [\"mode\"], valueColumn: \"_value\")\n  |> reduce(\n       fn: (r, accumulator) => ({_value: (r.nice + r.system + r.user) / (r.idle + r.nice + r.system + r.user)}),\n       identity: { _value: 0.0 }\n     )\n\ncpu_cores_used = join(tables: {key1: cpu_cores_total, key2: cpu_usage_percent}, on: [\"node\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _value: float(v: r.cpu_cores_total) * r._value }))\n  |> drop(columns: [\"cpu_cores_total\"])\n\nif \"${node}\" == \"all\"\nthen cpu_cores_used\n  |> group()\n  |> sum()\n  |> yield(name: \"cpu_cores_used\")\nelse cpu_cores_used\n  |> filter(fn: (r) => r.node == \"${node}\")\n  |> yield(name: \"cpu_cores_used\")"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "cpu_cores_total = from(bucket: \"metrics\")\n  |> range(start: -2m)\n  |> filter(fn: (r) => r._measurement == \"host.cpu_seconds_total\")\n  |> last()\n  |> keep(columns: [\"cpu\", \"node\"])\n  |> group(columns: [\"node\"])\n  |> rename(columns: {\"cpu\": \"_value\"},)\n  |> toInt()\n  |> max()\n  |> map(fn: (r) => ({ r with _value: r._value + 1 }))\n\nif \"${node}\" == \"all\"\n  then cpu_cores_total\n    |> group()\n    |> sum()\n    |> yield(name: \"cpu_cores_total\")\n  else cpu_cores_total\n    |> filter(fn: (r) => r.node == \"${node}\")\n    |> yield(name: \"cpu_cores_total\")"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "memory_used_bytes = from(bucket: \"metrics\")\n  |> range(start: -2m)\n  |> filter(fn: (r) => r._measurement == \"host.memory_used_bytes\")\n  |> last()\n  |> keep(columns: [\"_value\", \"node\"])\n\nif \"${node}\" == \"all\"\n  then memory_used_bytes\n    |> group()\n    |> sum()\n    |> yield(name: \"memory_used_bytes\")\n  else memory_used_bytes\n    |> filter(fn: (r) => r.node == \"${node}\")\n    |> yield(name: \"memory_used_bytes\")"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "memory_total_bytes = from(bucket: \"metrics\")\n  |> range(start: -2m)\n  |> filter(fn: (r) => r._measurement == \"host.memory_total_bytes\")\n  |> last()\n  |> keep(columns: [\"_value\", \"node\"])\n\nif \"${node}\" == \"all\"\n  then memory_total_bytes\n    |> group()\n    |> sum()\n    |> yield(name: \"memory_total_bytes\")\n  else memory_total_bytes\n    |> filter(fn: (r) => r.node == \"${node}\")\n    |> yield(name: \"memory_total_bytes\")"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "filesystem_used_bytes = from(bucket: \"metrics\")\n  |> range(start: -2m)\n  |> filter(fn: (r) => r.mountpoint == \"/\" and r._measurement == \"host.filesystem_used_bytes\")\n  |> last()\n  |> keep(columns: [\"node\", \"_value\"])\n\nif \"${node}\" == \"all\"\n  then filesystem_used_bytes\n    |> group()\n    |> sum()\n    |> yield(name: \"filesystem_used_bytes\")\n  else filesystem_used_bytes\n    |> filter(fn: (r) => r.node == \"${node}\")\n    |> yield(name: \"filesystem_used_bytes\")"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "filesystem_total_bytes = from(bucket: \"metrics\")\n  |> range(start: -2m)\n  |> filter(fn: (r) => r.mountpoint == \"/\" and r._measurement == \"host.filesystem_total_bytes\")\n  |> last()\n  |> keep(columns: [\"node\", \"_value\"])\n\nif \"${node}\" == \"all\"\n  then filesystem_total_bytes\n    |> group()\n    |> sum()\n    |> yield(name: \"filesystem_total_bytes\")\n  else filesystem_total_bytes\n    |> filter(fn: (r) => r.node == \"${node}\")\n    |> yield(name: \"filesystem_total_bytes\")\n "
    }
   ]
  },
  { "title": "Historical Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage (${interval} average)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"host.cpu_seconds_total\")\n  |> aggregateWindow(every: ${interval}, fn: mean)\n  |> pivot(rowKey: [\"_time\", \"node\"], columnKey: [\"mode\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: (r.nice + r.system + r.user) / (r.idle + r.nice + r.system + r.user) }))\n  |> keep(columns: [\"_time\", \"_value\", \"node\"])\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"host.memory_used_bytes\")\n  |> keep(columns: [\"_time\", \"_value\", \"node\"])\n"
    },
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"host.memory_total_bytes\")\n  |> rename(columns: {\"_value\": \"total\"})\n  |> keep(columns: [\"node\", \"total\"])\n"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r.mountpoint == \"/\" and r._measurement == \"host.filesystem_used_bytes\")\n  |> keep(columns: [\"_time\", \"_value\", \"node\"])\n"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"host.network_receive_bytes_total\")\n  |> keep(columns: [\"_time\", \"_value\", \"node\"])\n"
    }
   ]
  }
 ]
}