{
 "title": "Resources",
 "description": "Resource usage of each node in the Kubernetes cluster",
 "tags": [ "linux" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node:",
    "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"machine_cpu_cores\")\n  |> keep(columns: [\"node\"])\n  |> distinct(column: \"node\")\n  |> group()\n"
   }
  ]
 },
 "panels": [
  { "title": "${node} | Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Average CPU usage of the recent 5min ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -20s)\n  |> filter(fn: (r) => r.node == \"${node}\" and (r._measurement == \"host.load5\" or r._measurement == \"machine_cpu_cores\"))\n  |> last()\n  |> pivot(rowKey: [\"node\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n  |> reduce(\n       fn: (r, accumulator) => ({_value: r[\"host.load5\"] / r[\"machine_cpu_cores\"]}),\n       identity: { _value: 0.0 }\n     )\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -20s)\n  |> filter(fn: (r) => r.node == \"${node}\" and (r._measurement == \"host.memory_total_bytes\" or r._measurement == \"host.memory_used_bytes\"))\n  |> last()\n  |> drop(columns: [\"metric_type\"])\n  |> pivot(rowKey: [\"node\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n  |> reduce(\n       fn: (r, accumulator) => ({_value: r[\"host.memory_used_bytes\"] / r[\"host.memory_total_bytes\"]}),\n       identity: { _value: 0.0 }\n     )\n"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -20s)\n  |> filter(fn: (r) => r.node == \"${node}\" and (r._measurement == \"host.filesystem_total_bytes\" or r._measurement == \"host.filesystem_used_bytes\"))\n  |> last()\n  |> drop(columns: [\"metric_type\"])\n  |> pivot(rowKey: [\"node\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n  |> reduce(\n       fn: (r, accumulator) => ({_value: r[\"host.filesystem_used_bytes\"] / r[\"host.filesystem_total_bytes\"]}),\n       identity: { _value: 0.0 }\n     )\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -20s)\n  |> filter(fn: (r) => r._measurement == \"host.uptime\" and r.node == \"${node}\")\n  |> last()\n  |> keep(columns: [\"_value\", \"node\"])\n"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -20s)\n  |> filter(fn: (r) => r.node == \"${node}\" and r._measurement == \"host.load5\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -20s)\n  |> filter(fn: (r) => r.node == \"${node}\" and r._measurement == \"machine_cpu_cores\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -20s)\n  |> filter(fn: (r) => r.node == \"${node}\" and r._measurement == \"host.memory_used_bytes\")\n  |> last()\n  |> keep(columns: [\"_value\", \"node\"])\n"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -20s)\n  |> filter(fn: (r) => r.node == \"${node}\" and r._measurement == \"host.memory_total_bytes\")\n  |> last()\n  |> keep(columns: [\"_value\", \"node\"])\n"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -20s)\n  |> filter(fn: (r) => r.node == \"${node}\" and r._measurement == \"host.filesystem_used_bytes\")\n  |> last()\n  |> keep(columns: [\"node\", \"_value\"])\n"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -20s)\n  |> filter(fn: (r) => r.node == \"${node}\" and r._measurement == \"host.filesystem_total_bytes\")\n  |> last()\n  |> keep(columns: [\"node\", \"_value\"])\n"
    }
   ]
  },
  { "title": "Historical Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"host.load5\" or r._measurement == \"machine_cpu_cores\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> pivot(rowKey: [\"_time\", \"node\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r[\"host.load5\"] / r[\"machine_cpu_cores\"] }))\n  |> keep(columns: [\"_time\", \"_value\", \"node\"])\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"host.memory_total_bytes\" or r._measurement == \"host.memory_used_bytes\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> pivot(rowKey: [\"_time\", \"node\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r[\"host.memory_used_bytes\"] / r[\"host.memory_total_bytes\"] }))\n  |> keep(columns: [\"_time\", \"_value\", \"node\"])\n"
    },
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"host.memory_total_bytes\")\n  |> rename(columns: {\"_value\": \"total\"})\n  |> keep(columns: [\"node\", \"total\"])\n"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"host.filesystem_total_bytes\" or r._measurement == \"host.filesystem_used_bytes\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> pivot(rowKey: [\"_time\", \"node\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r[\"host.filesystem_used_bytes\"] / r[\"host.filesystem_total_bytes\"] }))\n  |> keep(columns: [\"_time\", \"_value\", \"node\"])\n"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => (r._measurement == \"host.network_receive_bytes_total\" or r._measurement == \"host.network_transmit_bytes_total\") and r.device != \"lo\")\n  |> map(fn: (r) => ({\n      r with _value: if r._measurement == \"host.network_receive_bytes_total\" then r._value else -r._value,\n             _measurement: if r._measurement == \"host.network_receive_bytes_total\" then \"received\" else \"transmitted\",\n    }))\n  |> keep(columns: [\"_measurement\", \"_time\", \"_value\", \"node\"])\n"
    }
   ]
  }
 ]
}