data_dir = "/vector-data-dir"

[sinks.monitoring_db]
type = "influxdb_metrics"
inputs = [
  "remove_cpu_node_metrics_fields",
  "remove_memory_node_metrics_fields",
  "remove_network_node_metrics_fields",
]
bucket = "${INFLUXDB_BUCKET}"
endpoint = "${INFLUXDB_ENDPOINT}"
org = "${INFLUXDB_ORG}"
token = "${INFLUXDB_TOKEN}"
  [sinks.monitoring_db.tags]
  node = "${VECTOR_SELF_NODE_NAME}"
