data_dir = "/vector-data-dir"

[sinks.monitoring_db]
type = "influxdb_metrics"
inputs = [
  "filter_unwanted_cpu_node_metrics",
  "filter_unwanted_memory_node_metrics",
  "filter_unwanted_network_node_metrics",
]
bucket = "${INFLUXDB_BUCKET}"
endpoint = "${INFLUXDB_ENDPOINT}"
org = "${INFLUXDB_ORG}"
token = "${INFLUXDB_TOKEN}"
  [sinks.monitoring_db.tags]
  node = "${VECTOR_SELF_NODE_NAME}"
