data_dir = "/vector-data-dir"

[sources.host_metrics]
type = "host_metrics"
collectors = ["cgroups", "cpu", "disk", "load", "host", "memory", "network"]
scrape_interval_secs = 15

[transforms.filter_unwanted_metrics]
type = "filter"
inputs = ["host_metrics"]
  [transforms.filter_unwanted_metrics.condition]
  type = "vrl"
  source = '''
    includes(
      [
        "cpu_seconds_total",
        "filesystem_total_bytes",
        "filesystem_used_bytes",
        "memory_total_bytes",
        "memory_used_bytes",
      ],
      .name,
    )
  '''

[sinks.monitoring_db]
type = "influxdb_metrics"
inputs = ["filter_unwanted_metrics"]
bucket = "${INFLUXDB_BUCKET}"
endpoint = "${INFLUXDB_ENDPOINT}"
org = "${INFLUXDB_ORG}"
token = "${INFLUXDB_TOKEN}"
  [sinks.monitoring_db.tags]
  node = "${VECTOR_SELF_NODE_NAME}"
