data_dir = "/vector-data-dir"

[sinks.log_db]
type = 'loki'
inputs = ['kubernetes_logs']
endpoint = '${LOKI_ENDPOINT}'
out_of_order_action = 'accept'
  [sinks.log_db.encoding]
  codec = 'json'
  [sinks.log_db.labels]
  container = '{{ kubernetes.container_name }}'
  namespace = '{{ kubernetes.pod_namespace }}'
  pod = '{{ kubernetes.pod_name }}'

[sinks.monitoring_db]
type = "influxdb_metrics"
inputs = [
  "remove_cpu_container_metrics_fields",
  "remove_filesystem_host_metrics_fields",
  "remove_host_metrics_fields",
  "remove_load_host_metrics_fields",
  "remove_memory_container_metrics_fields",
  "remove_memory_host_metrics_fields",
  "remove_network_container_metrics_fields",
  "remove_network_host_metrics_fields",
]
bucket = "${INFLUXDB_BUCKET}"
endpoint = "${INFLUXDB_ENDPOINT}"
org = "${INFLUXDB_ORG}"
token = "${INFLUXDB_TOKEN}"
  [sinks.monitoring_db.tags]
  node = "${VECTOR_SELF_NODE_NAME}"
