[sources.host_metrics]
type = "host_metrics"
collectors = ["cpu", "filesystem", "host", "memory", "network"]
scrape_interval_secs = 15

[transforms.host_metrics_routing]
type = "route"
inputs = ["host_metrics"]
  [transforms.host_metrics_routing.route]
  cpu = '.tags.collector == "cpu"'
  filesystem = '.tags.collector == "filesystem"'
  host = '.tags.collector == "host"'
  memory = '.tags.collector == "memory"'
  network = '.tags.collector == "network"'

[transforms.filter_unwanted_host_metrics]
type = "filter"
inputs = ["host_metrics_routing.host"]
  [transforms.filter_unwanted_host_metrics.condition]
  type = "vrl"
  source = 'includes(["uptime"], .name)'
