{
 "title": "Pod Resources",
 "description": "Resource usage of each pod in the Kubernetes cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "from(bucket: \"metrics\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"container_cpu_usage_seconds_total\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with _value: r.namespace }))\r\n  |> keep(columns: [\"_value\"])\r\n  |> distinct()\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Top 3",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"container_cpu_usage_seconds_total\" and r.namespace =~ /${namespace}/)\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> last()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: 3)\r\n  |> keep(columns: [\"_time\", \"_value\", \"pod\"])\r\n  "
    }
   ]
  },
  {
   "title": "Memory Top 3",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"container_memory_usage_bytes\" and r.namespace =~ /${namespace}/)\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> last()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: 3)\r\n  |> keep(columns: [\"_time\", \"_value\", \"pod\"])"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"container_cpu_usage_seconds_total\" and r.namespace =~ /${namespace}/)\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"pod\"])\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"container_memory_usage_bytes\" and r.namespace =~ /${namespace}/)\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"pod\"])\n"
    }
   ]
  }
 ]
}