{
 "title": "Vector",
 "description": "Telemetry data of the running Vector instances",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Received Events",
   "type": "timeseries",
   "description": "Events received by Vector every 15s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"vector.component_received_events_total\" and r.component_kind == \"source\")\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> group(columns: [\"_time\", \"node\"])\n  |> sum()\n  |> group(columns: [\"node\"])\n"
    }
   ]
  },
  {
   "title": "Sent Events",
   "type": "timeseries",
   "description": "Events sent to a sink by Vector every 15s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"vector.component_sent_events_total\" and r.component_kind == \"sink\")\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> group(columns: [\"_time\", \"node\"])\n  |> sum()\n  |> group(columns: [\"node\"])\n"
    }
   ]
  },
  {
   "title": "Received Event Bytes",
   "type": "timeseries",
   "description": "Event bytes received by Vector every 15s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"vector.component_received_event_bytes_total\" and r.component_kind == \"sink\")\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> group(columns: [\"_time\", \"node\"])\n  |> sum()\n  |> group(columns: [\"node\"])\n"
    }
   ]
  },
  {
   "title": "Sent Event Bytes",
   "type": "timeseries",
   "description": "Event bytes sent to a sink by Vector every 15s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"vector.component_sent_event_bytes_total\" and r.component_kind == \"sink\")\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> group(columns: [\"_time\", \"node\"])\n  |> sum()\n  |> group(columns: [\"node\"])\n"
    }
   ]
  }
 ]
}