[transforms.filter_unwanted_memory_container_metrics]
type = "filter"
inputs = ["container_metrics_routing.memory"]
  [transforms.filter_unwanted_memory_container_metrics.condition]
  type = "vrl"
  source = '.name == "container_memory_usage_bytes" && !is_nullish(.tags.pod)'

[transforms.remove_memory_container_metrics_fields]
type = "remap"
inputs = ["filter_unwanted_memory_container_metrics"]
source = """
  del(.tags.container)
  del(.tags.id)
  del(.tags.image)
  del(.tags.name)
"""
