VERSION 0.6

FROM DOCKERFILE -f deployment/kubernetes/image.Dockerfile .
WORKDIR /vector

ENV LOKI_ENDPOINT=https://loki
ENV VECTOR_INTERNAL_PORT=8686

test:
  COPY . .
  RUN vector test config/**/*.toml tests/**/*.yaml
