include:
  - template: Pages/HTML.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml # TODO: Remove

#workflow:
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  FORCE_COLOR: 'true'
  WORKDIR: documentation

stages:
  - build
  - deploy

🔧 Build:
  stage: build
  image:
    name: registry.gitlab.com/hendric-eckelt/infrastructure/earthly:0.6.15
    entrypoint: [""]
  before_script:
    - cd $WORKDIR
  script:
    - earthly +build
  artifacts:
    paths:
      - $WORKDIR/dist
    expire_in: 2 days

pages:
  dependencies:
    - "🔧 Build"
  rules: # TODO: Remove
    - when: always
  script:
    - mv $WORKDIR/dist public
