VERSION 0.6

FROM node:18-alpine
WORKDIR /documentation

build:
  COPY package.json yarn.lock ./
  RUN yarn install --frozen-lockfile
  COPY . .
  RUN yarn build
  SAVE ARTIFACT docs/.vitepress/dist /dist AS LOCAL ./dist
