name: 🖧 Kubernetes

on:
  merge_group:
  pull_request:
    branches:
      - main
      - next
    paths:
      - 'observability-stack/**/deployment/kubernetes/**/*'
  push:
    branches:
      - main
      - next
    paths:
      - 'observability-stack/**/deployment/kubernetes/**/*'

jobs:
  validate:
    runs-on: ubuntu-22.04
    env:
      FORCE_COLOR: 'true'
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v6

      - name: 🌎 Install Earthly
        run: |
          sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.30/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'
          earthly --version

      - name: 🕵️ Validate Kubernetes Deployment
        run: |
          earthly +validate-kubernetes-deployment
