name: Vector

on:
  merge_group:
  pull_request:
    branches:
      - main
      - next
    paths:
      - 'observability-stack/vector/**/*'
  push:
    branches:
      - main
      - next
    paths:
      - 'observability-stack/vector/**/*'

jobs:
  quality:
    runs-on: ubuntu-22.04
    env:
      FORCE_COLOR: 'true'
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v5

      - name: 🌎 Install Earthly
        run: |
          sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.30/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'
          earthly --version

      - name: 🧐 Validate
        working-directory: ./observability-stack/vector
        run: |
          earthly +validate

      - name: 🧪 Test
        working-directory: ./observability-stack/vector
        run: |
          earthly +test
